name: 'Build'

on:
  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]
  workflow_dispatch:

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v2
    - uses: actions/setup-dotnet@v1
      with:
        dotnet-version: 6.x
    - run: dotnet restore
    - uses: zcong1993/setup-timezone@master
      with:
        timezone: Europe/Brussels
    - run: dotnet test SeatsioDotNet.Test --verbosity normal
      env:
        DEMO_COMPANY_SECRET_KEY: ${{ secrets.DEMO_COMPANY_SECRET_KEY }}
